### ISSUE TITLE
Corpses

### ISSUE THREAD

**Issue by mafagafogigante** [mafagafogigante/dungeon#90]
@neurolytic Let's get this going? Set a few milestones, divide tasks and implement corpses?

**Comment by mafagafogigante** [comment]
Also, do you think that a chat mechanism would increase our productivity? Even though issues and e-mail work, this resembles real mail messages, we can collaborate but working together in real time seems impossible.

**Comment by neurolytic** [comment]
Okay. I don't have anything to chat on right now, what should we use?

**Comment by mafagafogigante** [comment]
I've got school tomorrow at 7 (I'm at GMT-3 so now it is 00:18 here) and I'm laying on my bed. I've got a HipChat group and will invite you tomorrow. OK?

It may be quite useful when we work concomitantly. Good night, pal.

**Comment by neurolytic** [comment]
Sounds good, have a good night.

**Comment by neurolytic** [comment]
I keep trying to poke at this from different directions to upturn as few other parts of the code as possible, and... it's not easy. The way you have items is currently very rigid and doesn't lend itself to dynamic items. The least-disruptive thing I can think of is extending Item with a BodyPart (name not important) subclass that holds a reference to a creature and overrides the necessary Item methods so that name, weight, and so on return values custom to the referenced creature. In order to do this we either need to extend ItemBlueprint (meaning it can't be final anymore) or add a field to ItemBlueprint that allows it to identify as a bodypart (and either have its stored weight be a % of creature weight, or have ANOTHER field only for bodyparts called "% of creature weight"), _OR_ make a separate BodyPartBlueprint that doesn't extend anything--though this would cause a lot of code duplication.

**Comment by mafagafogigante** [comment]
Simple suggestion: for every creature we load, write also a ItemBlueprint (soon to become ItemPreset - I think) for its corpse. What do you think?

**Comment by neurolytic** [comment]
I'm not sure if you ever read the comment I posted on my own branch before I deleted it, but I mentioned that method and IMO it's not ideal because eventually, when we add more than just Wolf Corpse, but things like Wolf Skeleton, Wolf Hide, Wolf Claws, Wolf Teeth, Wolf Meat, COOKED Wolf Meat... and whatever other level of detail we want to take it to, we'll end up storing totally monstrous amounts of blueprints. Plus any kind of necromancy type effects (animate dead, raise dead, raise spirit, whatever) would probably need the item to know what creature it came from.

Why do you prefer preset over blueprint? Following the literal pattern behind not using 'lifespan', preset doesn't really fit grammatically, but blueprint fits precisely.

**Comment by mafagafogigante** [comment]
I think I have already written some reasons for preset over blueprint somewhere else. Anyways, creating more classes will make this less data-driven. In the end, all those things are items. And Cooked Wolf Meat should be a completely different Item from Wolf Meat (or Raw Wolf Meat), besides this cases should only be discussed when we implement crafting.

Currently, we are only aiming for corpses and butchery, creating a blueprint (or preset) for ``creature.getName() + " Corpse"`` (if the creature has a corpse) with the creature's weight and allowing the player to butcher it to get some meat ``creature.getName() + " Flesh"`` if the creature has a certain tag would be ideal.

"totally monstrous amounts of blueprints" - let's talk science. 100 monsters. 10 items per monster (whoa). 1000 items. Suppose 3 KB per item. 3 MB or RAM. No big deal. End of discussion. Anything to add?

**Comment by neurolytic** [comment]
Fair enough. Have you ever played Dwarf Fortress? I was taking a certain amount of inspiration from that in my body part stuff. In that game, there's like, Left First Finger, Left Second Finger, Right Fifth Finger, Right Hand, Left Forearm... and so on. There's also a kajillion creatures. So I was thinking in that scale, but I don't suppose that's what you're going for :P

**Comment by mafagafogigante** [comment]
There is not a defined strict goal set out yet. Mind going over to HipChat?
